=== bangarharshit/Resume-Parser/src/main/resources/schema/resume_type1.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/Welcome9",
  "definitions": {
    "Welcome9": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "education": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Education"
          }
        },
        "id": {
          "type": "string"
        },
        "industries": {
          "type": "array",
          "items": {}
        },
        "title": {
          "type": "string"
        },
        "location": {
          "type": "string"
        },
        "timestamp": {
          "type": "integer"
        },
        "email": {
          "type": "string"
        },
        "firstname": {
          "type": "string"
        },
        "raw_profile_link": {
          "type": "string",
          "format": "uri",
          "qt-uri-protocols": [
            "https"
          ],
          "qt-uri-extensions": [
            ".png"
          ]
        },
        "lastname": {
          "type": "string"
        },
        "endorsements": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Endorsement"
          }
        },
        "phone": {
          "type": "string"
        },
        "gender": {
          "type": "string"
        },
        "enc_id": {
          "type": "string"
        },
        "experience": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Experience"
          }
        },
        "summary": {
          "type": "string"
        },
        "fullname": {
          "type": "string"
        }
      },
      "required": [
        "education",
        "email",
        "enc_id",
        "endorsements",
        "experience",
        "firstname",
        "fullname",
        "gender",
        "id",
        "industries",
        "lastname",
        "location",
        "phone",
        "raw_profile_link",
        "summary",
        "timestamp",
        "title"
      ],
      "title": "Welcome9"
    },
    "Education": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "edited": {
          "type": "null"
        },
        "school": {
          "type": "string"
        },
        "event_type": {
          "type": "string"
        },
        "degree": {
          "type": "string"
        },
        "skills": {
          "type": "array",
          "items": {}
        },
        "major": {
          "type": "string"
        },
        "awards": {
          "type": "array",
          "items": {}
        },
        "abbr": {
          "type": "string"
        },
        "time": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "integer"
          }
        },
        "duration": {
          "type": "integer"
        },
        "addl_json": {
          "$ref": "#/definitions/AddlJSON"
        },
        "image_url": {
          "anyOf": [
            {
              "type": "null"
            },
            {
              "type": "string",
              "format": "uri",
              "qt-uri-protocols": [
                "https"
              ],
              "qt-uri-extensions": [
                ".png"
              ]
            }
          ]
        },
        "description": {
          "type": "string"
        }
      },
      "required": [
        "abbr",
        "addl_json",
        "awards",
        "degree",
        "description",
        "duration",
        "edited",
        "event_type",
        "image_url",
        "major",
        "school",
        "skills",
        "time"
      ],
      "title": "Education"
    },
    "AddlJSON": {
      "type": "object",
      "additionalProperties": false,
      "title": "AddlJSON"
    },
    "Endorsement": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "work": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "metadata": {
          "type": "string"
        }
      },
      "required": [
        "description",
        "metadata",
        "work"
      ],
      "title": "Endorsement"
    },
    "Experience": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "edited": {
          "type": "null"
        },
        "description": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "work": {
          "type": "string"
        },
        "growth_percentile": {
          "type": "null"
        },
        "addl_json": {
          "$ref": "#/definitions/AddlJSON"
        },
        "location": {
          "type": "string"
        },
        "time": {
          "$ref": "#/definitions/Time"
        },
        "duration": {
          "type": "integer"
        },
        "user_verified_skills": {
          "type": "boolean"
        },
        "event_type": {
          "type": "string"
        }
      },
      "required": [
        "addl_json",
        "description",
        "duration",
        "edited",
        "event_type",
        "growth_percentile",
        "location",
        "time",
        "title",
        "user_verified_skills",
        "work"
      ],
      "title": "Experience"
    },
    "Time": {
      "anyOf": [
        {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        {
          "type": "string"
        }
      ],
      "title": "Time"
    }
  }
}

=== bangarharshit/Resume-Parser/src/main/resources/resumes/resume1.json
{
  "education": [
    {
      "edited": null,
      "school": "ABPS School",
      "event_type": "education",
      "degree": "MS",
      "skills": [],
      "major": "",
      "awards": [],
      "abbr": "ucsb",
      "time": [
        "2005",
        "2007"
      ],
      "duration": 0,
      "addl_json": {},
      "image_url": "https://sample_images.com/1.png",
      "description": "I did my MS, Masters in Computers Science at ABCD from 2005 to 2007."
    },
    {
      "edited": null,
      "school": "XYZ, Bangalore",
      "event_type": "education",
      "degree": "B.E",
      "skills": [],
      "major": "",
      "awards": [],
      "abbr": "ub",
      "time": [
        "1996",
        "2000"
      ],
      "duration": 0,
      "addl_json": {},
      "image_url": null,
      "description": "Did my B.E in Computer science from 1996 to 2000."
    }
  ],
  "id": "sample_candidate_id",
  "industries": [],
  "title": "Software Engineer",
  "location": "ABC Bay Area",
  "timestamp": 1499811934,
  "email": "johndoe@candidate.com",
  "firstname": "John",
  "raw_profile_link": "https://sample_images.com/1.png",
  "lastname": "Doe",
  "endorsements": [
    {
      "work": "",
      "description": "HLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      "metadata": ""
    },
    {
      "work": "",
      "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      "metadata": ""
    }
  ],
  "phone": "+9112312312",
  "gender": "male",
  "enc_id": "VD1b2OZK",
  "experience": [
    {
      "edited": null,
      "description": "",
      "title": "Software Engineer, Big Data,Data Infrastructure, XYZ",
      "work": "xyz",
      "growth_percentile": null,
      "addl_json": {},
      "location": "",
      "time": "",
      "duration": 0,
      "user_verified_skills": false,
      "event_type": "experience"
    },
    {
      "edited": null,
      "description": "Building big-data pipeline infrastructure for big-chain restaurants for generating guest analytics using Hadoop, Hive, HBase, Sqoop, Java programming, SQL and shell scripting. This data pipeline delivers user-segmentation reports, menu-item-segmentation reports and business reports for these restaurants using their POS (Point Of Sale) system data as input. \nAs Software Engineer, I was involved in the end-to-end design and development of this data pipeline.",
      "title": "Junior Software Engineer, Big Data,Data Infrastructure, ABC",
      "work": "abc",
      "growth_percentile": null,
      "addl_json": {},
      "location": "",
      "time": [
        "Oct 2015",
        "Present"
      ],
      "duration": 1374,
      "user_verified_skills": false,
      "event_type": "experience"
    }
  ],
  "summary": "I am a senior level developer with several years experience in the field of Java development with expertise in Big Data, Cloud computing Hadoop technologies like map-reduce, Pig, Hive, and HDFS and also realtime technologies like Storm. I also have experience in web development. I have done my MS in ABCD and XYZ, both highly reputed colleges and both the degrees in Computer science. \n\nSpecialties: Expertise in Java programming, Cloud computing technologies like Hadoop technologies like map-reduce, Hive, Pig and HDFS, . I also have considerable experience in C++ developement on Linux and J2EE based application development",
  "fullname": "John Doe"
}
